### ISSUE TITLE
Registering maps no longer works

### ISSUE THREAD

**Issue by Braffolk** [BigFaceMaster/echarts-next-for-react#1]
Calling echarts.registerMap does not work with this version and echarts 5.0.1. The console says "index.js:1 Map xxxxx not exists. The GeoJSON of the map must be provided". The geojson was provided and the echarts.registerMap was called before creating the echarts element.

**Comment by BigFaceMaster** [comment]
Could you show your code to me?

**Comment by BigFaceMaster** [comment]
how about this docs: https://echarts.apache.org/en/option.html#series-map
