### ISSUE TITLE
reduce to get small bundle size?

### ISSUE THREAD

**Issue by rimsila** [BigFaceMaster/echarts-next-for-react#2]
I have big bundle size in my project I just use only Bar and Pie Chart. thanks you
![image](https://user-images.githubusercontent.com/51617383/109639924-64adaa80-7b82-11eb-823d-370380c03b38.png)

**Comment by BigFaceMaster** [comment]
I'm trying to optimize this.

**Comment by BigFaceMaster** [comment]
Published new release.

**Comment by BigFaceMaster** [comment]
I had publish new release.

**Comment by BigFaceMaster** [comment]
Actuallly, you can get my source code, and import component what you need.
